### ISSUE TITLE
Different pub_resolution options for video and depth

### ISSUE THREAD

**Issue by gabor-kovacs** [stereolabs/zed-ros2-wrapper#141]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

There used to be separate parameters in `common.yaml`: `video.img_downsample_factor` and `depth.depth_downsample_factor`
so It was possible to publish a higher resolution image and  lower resolution point cloud.

These were removed and now `general.pub_resolution` is used instead.

Is it possible to use the new "simplified" method but give more control e.g. create a separate parameter for `video.pub_resolution` and `depth.pub_resolution` instead?

**Comment by Myzhar** [comment]
Hi @gabor-kovacs 
this was a development choice in order to publish coherent color and depth information (different parameters caused problems for many users). For this reason, the feature that you are asking for will not be reintroduced.
However, you can modify the source code to add it if you need it. It's relatively straightforward.
