### ISSUE TITLE
Zed2i SVO Recording missing angular acceleration

### ISSUE THREAD

**Issue by JonasFrey96** [stereolabs/zed-ros2-wrapper#259]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When recording SVO files there is no angular velocity stored. 
It would be great to have the raw imu topic stored correctly. 

### Steps to Reproduce

1. Record an SVO file

### Expected Result

All angular velocity and acceleration stored at IMU frequency!

### Actual Result

No angular velocity ais stored.

### ZED Camera model

ZED2i

### Environment

```shell
Jetson Orin 
SDK 4.1
```

### Anything else?

Thanks a lot

**Comment by Myzhar** [comment]
Hi @JonasFrey96 
this is not something related to the ROS 2 Wrapper because it uses the SVO recording module of the ZED SDK.
Please test SVO recording with ZED Explorer and check that the information is missing also in that case and eventually write an email to support@stereolabs.com adding all the relevant information.
